# **Exercise 1 Solution**

In [ ]:
!pip install -q pyomo

In [ ]:
from pyomo.environ import *

In [ ]:
import numpy as np

In [ ]:
coef = np.loadtxt('lab4_ex1_coef.txt', delimiter=',')

In [ ]:
print(coef.shape)
print('Num rows:' , coef.shape[0])
print('Num cols:' , coef.shape[1])

(6, 7)
Num rows: 6
Num cols: 7


In [ ]:
print(coef)

[[  0.65   0.75  -5.85  -8.35 -12.38  30.     0.  ]
 [ -0.5    0.    -3.8   -0.9    0.9    0.    24.8 ]
 [  1.     0.     0.    -1.     0.    -1.     0.8 ]
 [  0.    -2.9   -1.9    0.     0.    -0.9  -71.4 ]
 [  0.     0.     0.     4.7    8.02   6.15  95.  ]
 [ -0.7   -1.4    7.9   -2.9    0.9    0.   -47.  ]]


In [ ]:
model1 = ConcreteModel()

In [ ]:
N = coef.shape[1]-1
M = coef.shape[0]-1

In [ ]:
obj_coef = coef[0,:-1]
print(obj_coef.shape)
print(obj_coef)

(6,)
[  0.65   0.75  -5.85  -8.35 -12.38  30.  ]


In [ ]:
constr_coef = coef[1:,:-1]
print(constr_coef.shape)
print(constr_coef)

(5, 6)
[[-0.5   0.   -3.8  -0.9   0.9   0.  ]
 [ 1.    0.    0.   -1.    0.   -1.  ]
 [ 0.   -2.9  -1.9   0.    0.   -0.9 ]
 [ 0.    0.    0.    4.7   8.02  6.15]
 [-0.7  -1.4   7.9  -2.9   0.9   0.  ]]


In [ ]:
constr_rhs = coef[1:,-1]
print(constr_rhs.shape)
print(constr_rhs)


(5,)
[ 24.8   0.8 -71.4  95.  -47. ]


In [ ]:
lower_bound = 0
upper_bound = np.inf

In [ ]:
col_indices = np.arange(N)
print(col_indices)

[0 1 2 3 4 5]


In [ ]:
model1.x = Var(col_indices)

In [ ]:
row_indices = np.arange(M)
print(row_indices)

[0 1 2 3 4]


In [ ]:
model1.constraints = ConstraintList()

In [ ]:
for i in row_indices:
  model1.constraints.add(summation(constr_coef[i],model1.x) <= constr_rhs[i])

In [ ]:
for j in col_indices:
  model1.x[j].setlb(lower_bound)
  model1.x[j].setub(upper_bound)

In [ ]:
model1.objective = Objective(expr = summation(obj_coef,model1.x), sense=maximize)

In [ ]:
model1.pprint()

2 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :    5 : {1, 2, 3, 4, 5}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :    6 : {0, 1, 2, 3, 4, 5}

1 Var Declarations
    x : Size=6, Index=x_index
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          0 :     0 :  None :  None : False :  True :  Reals
          1 :     0 :  None :  None : False :  True :  Reals
          2 :     0 :  None :  None : False :  True :  Reals
          3 :     0 :  None :  None : False :  True :  Reals
          4 :     0 :  None :  None : False :  True :  Reals
          5 :     0 :  None :  None : False :  True :  Reals

1 Objective Declarations
    objective : Size=1, Index=None, Active=True
        Key  : Active : Sense    : Expression
        None :   True : maximize : 0.65*x[0] + 0.75*x[1] - 5.85*x[2

In [ ]:
!apt-get install -y -qq coinor-cbc

Selecting previously unselected package coinor-libcoinutils3v5.
(Reading database ... 155676 files and directories currently installed.)
Preparing to unpack .../0-coinor-libcoinutils3v5_2.10.14+repack1-1_amd64.deb ...
Unpacking coinor-libcoinutils3v5 (2.10.14+repack1-1) ...
Selecting previously unselected package coinor-libosi1v5.
Preparing to unpack .../1-coinor-libosi1v5_0.107.9+repack1-1_amd64.deb ...
Unpacking coinor-libosi1v5 (0.107.9+repack1-1) ...
Selecting previously unselected package coinor-libclp1.
Preparing to unpack .../2-coinor-libclp1_1.16.11+repack1-1_amd64.deb ...
Unpacking coinor-libclp1 (1.16.11+repack1-1) ...
Selecting previously unselected package coinor-libcgl1.
Preparing to unpack .../3-coinor-libcgl1_0.59.10+repack1-1_amd64.deb ...
Unpacking coinor-libcgl1 (0.59.10+repack1-1) ...
Selecting previously unselected package coinor-libcbc3.
Preparing to unpack .../4-coinor-libcbc3_2.9.9+repack1-1_amd64.deb ...
Unpacking coinor-libcbc3 (2.9.9+repack1-1) ...
Selecting p

In [ ]:
opt_cbc = SolverFactory('cbc')

# Exercise 1(7) Solution

In [ ]:
result = opt_cbc.solve(model1)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

  - termination condition: unbounded
  - message from solver: <undefined>


Solver status: warning
Solver termination condition: unbounded


In this problem solution is unbounded. because solver status is warning or solver termination condition is unbounded.

# Exercise 1(9) Solution

In [ ]:
model1.objective.set_sense(minimize)

In [ ]:
model1.pprint()

2 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :    5 : {1, 2, 3, 4, 5}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :    6 : {0, 1, 2, 3, 4, 5}

1 Var Declarations
    x : Size=6, Index=x_index
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          0 :     0 :  None :  None : False :  True :  Reals
          1 :     0 :  None :  None : False :  True :  Reals
          2 :     0 :  None :  None : False :  True :  Reals
          3 :     0 :  None :  None : False :  True :  Reals
          4 :     0 :  None :  None : False :  True :  Reals
          5 :     0 :  None :  None : False :  True :  Reals

1 Objective Declarations
    objective : Size=1, Index=None, Active=True
        Key  : Active : Sense    : Expression
        None :   True : minimize : 0.65*x[0] + 0.75*x[1] - 5.85*x[2

In [ ]:
result = opt_cbc.solve(model1)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

  - termination condition: unbounded
  - message from solver: <undefined>


Solver status: warning
Solver termination condition: unbounded


for checking optimal function value ....firstly i have check by changing sense maximize to minimize but in this case also got a unbounded solution.

then in constraints maximum upper bound is 95 so I am choose a one value greater than 95 for upper bound i.e upper bound is choosen 420

In [ ]:
model1.objective.set_sense(maximize)

In [ ]:
#reset the upper bound
for i in col_indices:
  model1.x[i].setub(420)
model1.pprint()

2 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :    5 : {1, 2, 3, 4, 5}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :    6 : {0, 1, 2, 3, 4, 5}

1 Var Declarations
    x : Size=6, Index=x_index
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          0 :     0 :  None :   420 : False :  True :  Reals
          1 :     0 :  None :   420 : False :  True :  Reals
          2 :     0 :  None :   420 : False :  True :  Reals
          3 :     0 :  None :   420 : False :  True :  Reals
          4 :     0 :  None :   420 : False :  True :  Reals
          5 :     0 :  None :   420 : False :  True :  Reals

1 Objective Declarations
    objective : Size=1, Index=None, Active=True
        Key  : Active : Sense    : Expression
        None :   True : maximize : 0.65*x[0] + 0.75*x[1] - 5.85*x[2

In [ ]:
result = opt_cbc.solve(model1)
print(result)

print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)


Problem: 
- Name: unknown
  Lower bound: 788.9752846
  Upper bound: 788.9752846
  Number of objectives: 1
  Number of constraints: 6
  Number of variables: 7
  Number of nonzeros: 3
  Sense: maximize
Solver: 
- Status: ok
  User time: -1.0
  System time: 0.0
  Wallclock time: 0.0
  Termination condition: optimal
  Termination message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
  Statistics: 
    Branch and bound: 
      Number of bounded subproblems: None
      Number of created subproblems: None
    Black box: 
      Number of iterations: 2
  Error rc: 0
  Time: 0.012163639068603516
Solution: 
- number of solutions: 0
  number of solutions displayed: 0

Solver status: ok
Solver termination condition: optimal


In [ ]:
print('\nObjective = ', model1.objective())

print('\nDecision Variables')
for i in col_indices:
  print('x[',i,'] = ', model1.x[i].value)

print('\nConstraints')
model1.constraints.display()


Objective =  788.9752701

Decision Variables
x[ 0 ] =  16.247154
x[ 1 ] =  420.0
x[ 2 ] =  0.0
x[ 3 ] =  0.0
x[ 4 ] =  0.0
x[ 5 ] =  15.447154

Constraints
constraints : Size=5
    Key : Lower : Body               : Upper
      1 :  None :          -8.123577 :  24.8
      2 :  None : 0.7999999999999989 :   0.8
      3 :  None :      -1231.9024386 : -71.4
      4 :  None :         94.9999971 :  95.0
      5 :  None :       -599.3730078 : -47.0


when i change the upper bound then i got the optimal objective function value.

# constraints 1
Constraint 1 is inactive because LHS and RHS are not equal
# constraints 2
Constraint 2 is active because LHS and RHS are equal
# constraints 3
Constraint 3 is inactive because LHS and RHS are not equal
# constraints 4
Constraint 4 is active because LHS and RHS are equal
# constraints 5
Constraint 5 is inactive because LHS and RHS are not equal
