# *Exercise 2 Solution*

#  Exercise 2(1) Solution

$ \text{Define a indicator function which take a value 0 and 1, } \\ x_i = 1 \text{ if } C_j \text{ is selected , } 0 \text{ otherwise} \\ \text{ here } i = 1,2,3,....10 \text{ and } j = 0,1,2,....9 \\ $

 $ \text{As a credit course example, let us consider} $
$\max \ 4 x_1 + 3 x_2 + 6 x_3 + 5 x_4 + 2 x_5 + 6 x_6 + 4 x_7 + 8 x_8 + 8 x_9 + 6 x_{10}\\ \text{ s.t. }   
4 x_1 + 3 x_2 + 6 x_3 + 5 x_4 + 2 x_5 + 6 x_6 + 4 x_7 + 8 x_8 + 8 x_9 + 6 x_{10} \geq 26 \\ x_3+ x_8 \leq 1 \\ x_2+ x_{10} \leq 1 \\ x_3+ x_9 \leq 1 \\ -x_5 + x_{10} \leq 0 \\ 1 \leq x_1 + x_2 + x_3+ x_4 \leq 2 \\ x_6 + x_{10} \leq 1 \\ x_7 + x_9 + x_{10} \leq 2 \\ 4 \leq x_1 + x_2 + x_3 + x_4 + x_5 + x_6 + x_7 + x_8 + x_9 + x_{10} \leq 8$.


In [142]:
!pip install -q pyomo

In [143]:
from pyomo.environ import *

In [144]:
import numpy as np

In [145]:
model2 = ConcreteModel()

In [146]:
N = 10
M = 11

In [147]:
obj_coef_c = np.array([4,3,6,5,2,6,4,8,8,6])

constr_coef_A = np.array([[-4,-3,-6,-5,-2,-6,-4,-8,-8,-6],
                          [0,0,1,0,0,0,0,1,0,0],
                          [0,1,0,0,0,0,0,0,0,1],
                          [0,0,1,0,0,0,0,0,1,0],
                          [0,0,0,0,-1,0,0,0,0,1],
                          [1,1,1,1,0,0,0,0,0,0],
                          [-1,-1,-1,-1,0,0,0,0,0,0],
                          [0,0,0,0,0,1,0,0,0,1],
                          [0,0,0,0,0,0,1,0,1,1],
                          [1,1,1,1,1,1,1,1,1,1],
                          [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1]
                          ])

constr_coef_rhs = np.array([-26,1,1,1,0,2,-1,1,2,8,-4])

row_indices = np.arange(M)
col_indices = np.arange(N)

print(row_indices)
print(col_indices)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]


In [148]:
model2.x = Var(col_indices, domain = Binary)
model2.constraints = ConstraintList()

In [149]:
for i in row_indices:
  model2.constraints.add(sum(constr_coef_A[i][j]*model2.x[j] for j in col_indices) <= constr_coef_rhs[i])

In [150]:
model2.objective = Objective(expr = summation(obj_coef_c , model2.x) , sense = maximize )

In [151]:
model2.pprint()

2 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   11 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   10 : {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

1 Var Declarations
    x : Size=10, Index=x_index
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          0 :     0 :  None :     1 : False :  True : Binary
          1 :     0 :  None :     1 : False :  True : Binary
          2 :     0 :  None :     1 : False :  True : Binary
          3 :     0 :  None :     1 : False :  True : Binary
          4 :     0 :  None :     1 : False :  True : Binary
          5 :     0 :  None :     1 : False :  True : Binary
          6 :     0 :  None :     1 : False :  True : Binary
          7 :     0 :  None :     1 : False :  True : Binary
          8 :     0 :  None :   

In [152]:
!apt-get install -y -qq coinor-cbc

In [153]:
opt_cbc = SolverFactory('cbc')

#  Exercise 2(3) Solution

In [154]:
result = opt_cbc.solve(model2)
print(result)

print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)
print('Solver time:',result.solver.time)


Problem: 
- Name: unknown
  Lower bound: 37.0
  Upper bound: 37.0
  Number of objectives: 1
  Number of constraints: 11
  Number of variables: 10
  Number of binary variables: 10
  Number of integer variables: 10
  Number of nonzeros: 10
  Sense: maximize
Solver: 
- Status: ok
  User time: -1.0
  System time: 0.0
  Wallclock time: 0.0
  Termination condition: optimal
  Termination message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
  Statistics: 
    Branch and bound: 
      Number of bounded subproblems: 0
      Number of created subproblems: 0
    Black box: 
      Number of iterations: 0
  Error rc: 0
  Time: 0.020865917205810547
Solution: 
- number of solutions: 0
  number of solutions displayed: 0

Solver status: ok
Solver termination condition: optimal
Solver time: 0.020865917205810547


In [155]:
# display solution
print('\nObjective = ', model2.objective())

print('\nDecision Variables')
for i in col_indices:
  print('x[',i,'] = ', model2.x[i].value)
print('\nConstraints')
model2.constraints.display()


Objective =  37.0

Decision Variables
x[ 0 ] =  1.0
x[ 1 ] =  0.0
x[ 2 ] =  0.0
x[ 3 ] =  1.0
x[ 4 ] =  1.0
x[ 5 ] =  1.0
x[ 6 ] =  1.0
x[ 7 ] =  1.0
x[ 8 ] =  1.0
x[ 9 ] =  0.0

Constraints
constraints : Size=11
    Key : Lower : Body  : Upper
      1 :  None : -37.0 : -26.0
      2 :  None :   1.0 :   1.0
      3 :  None :   0.0 :   1.0
      4 :  None :   1.0 :   1.0
      5 :  None :  -1.0 :   0.0
      6 :  None :   2.0 :   2.0
      7 :  None :  -2.0 :  -1.0
      8 :  None :   1.0 :   1.0
      9 :  None :   2.0 :   2.0
     10 :  None :   7.0 :   8.0
     11 :  None :  -7.0 :  -4.0


#  Exercise 2(4) Solution

In [156]:
!pip install -q pyomo

In [157]:
from pyomo.environ import *

In [158]:
import numpy as np

In [159]:
model2_4 = ConcreteModel()

In [160]:
N = 10
M = 11

In [161]:
lb = np.array([0]*10)
ub = np.array([1]*10)

In [162]:
obj_coef_c = np.array([4,3,6,5,2,6,4,8,8,6])

constr_coef_A = np.array([[-4,-3,-6,-5,-2,-6,-4,-8,-8,-6],
                          [0,0,1,0,0,0,0,1,0,0],
                          [0,1,0,0,0,0,0,0,0,1],
                          [0,0,1,0,0,0,0,0,1,0],
                          [0,0,0,0,-1,0,0,0,0,1],
                          [1,1,1,1,0,0,0,0,0,0],
                          [-1,-1,-1,-1,0,0,0,0,0,0],
                          [0,0,0,0,0,1,0,0,0,1],
                          [0,0,0,0,0,0,1,0,1,1],
                          [1,1,1,1,1,1,1,1,1,1],
                          [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1]
                          ])

constr_coef_rhs = np.array([-26,1,1,1,0,2,-1,1,2,8,-4])

row_indices = np.arange(M)
col_indices = np.arange(N)

print(row_indices)
print(col_indices)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]


In [163]:
model2_4.x = Var(col_indices, domain = Reals)
model2_4.constraints = ConstraintList()

In [164]:
for i in col_indices:
  model2_4.x[i].setlb(lb[i])
  model2_4.x[i].setub(ub[i])

In [165]:
for i in row_indices:
  model2_4.constraints.add(sum(constr_coef_A[i][j]*model2_4.x[j] for j in col_indices) <= constr_coef_rhs[i])

In [166]:
model2_4.objective = Objective(expr = summation(obj_coef_c , model2_4.x) , sense = maximize )
model2_4.pprint()

2 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   11 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   10 : {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

1 Var Declarations
    x : Size=10, Index=x_index
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          0 :     0 :  None :     1 : False :  True :  Reals
          1 :     0 :  None :     1 : False :  True :  Reals
          2 :     0 :  None :     1 : False :  True :  Reals
          3 :     0 :  None :     1 : False :  True :  Reals
          4 :     0 :  None :     1 : False :  True :  Reals
          5 :     0 :  None :     1 : False :  True :  Reals
          6 :     0 :  None :     1 : False :  True :  Reals
          7 :     0 :  None :     1 : False :  True :  Reals
          8 :     0 :  None :   

In [167]:
!apt-get install -y -qq coinor-cbc

In [168]:
opt_cbc = SolverFactory('cbc')

In [169]:
result = opt_cbc.solve(model2_4)
print(result)

print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)


Problem: 
- Name: unknown
  Lower bound: 37.0
  Upper bound: 37.0
  Number of objectives: 1
  Number of constraints: 12
  Number of variables: 11
  Number of nonzeros: 10
  Sense: maximize
Solver: 
- Status: ok
  User time: -1.0
  System time: 0.0
  Wallclock time: 0.0
  Termination condition: optimal
  Termination message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
  Statistics: 
    Branch and bound: 
      Number of bounded subproblems: None
      Number of created subproblems: None
    Black box: 
      Number of iterations: 4
  Error rc: 0
  Time: 0.019642114639282227
Solution: 
- number of solutions: 0
  number of solutions displayed: 0

Solver status: ok
Solver termination condition: optimal


In [170]:
# display solution
print('\nObjective = ', model2_4.objective())

print('\nDecision Variables')
for i in col_indices:
  print('x[',i,'] = ', model2_4.x[i].value)
print('\nConstraints')
model2_4.constraints.display()


Objective =  37.0

Decision Variables
x[ 0 ] =  1.0
x[ 1 ] =  0.0
x[ 2 ] =  0.0
x[ 3 ] =  1.0
x[ 4 ] =  1.0
x[ 5 ] =  1.0
x[ 6 ] =  1.0
x[ 7 ] =  1.0
x[ 8 ] =  1.0
x[ 9 ] =  0.0

Constraints
constraints : Size=11
    Key : Lower : Body  : Upper
      1 :  None : -37.0 : -26.0
      2 :  None :   1.0 :   1.0
      3 :  None :   0.0 :   1.0
      4 :  None :   1.0 :   1.0
      5 :  None :  -1.0 :   0.0
      6 :  None :   2.0 :   2.0
      7 :  None :  -2.0 :  -1.0
      8 :  None :   1.0 :   1.0
      9 :  None :   2.0 :   2.0
     10 :  None :   7.0 :   8.0
     11 :  None :  -7.0 :  -4.0


In this case answer is same as in domain binary and in domain reals.

#  Exercise 2(6) Solution

In [171]:
model2_6 = ConcreteModel()

In [172]:
N = 11
M = 12

In [173]:
obj_coef_c = np.array([4,3,6,5,2,6,4,8,8,6,12])

constr_coef_A = np.array([[-4,-3,-6,-5,-2,-6,-4,-8,-8,-6,-12],
                          [0,0,1,0,0,0,0,1,0,0,0],
                          [0,1,0,0,0,0,0,0,0,1,0],
                          [0,0,1,0,0,0,0,0,1,0,0],
                          [0,0,0,0,-1,0,0,0,0,1,0],
                          [1,1,1,1,0,0,0,0,0,0,0],
                          [-1,-1,-1,-1,0,0,0,0,0,0,0],
                          [0,0,0,0,0,1,0,0,0,1,0],
                          [0,0,0,0,0,0,1,0,1,1,0],
                          [1,1,1,1,1,1,1,1,1,1,1],
                          [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                          [0,0,0,0,0,1,1,0,0,0,1]
                          ])

constr_coef_rhs = np.array([-26,1,1,1,0,2,-1,1,2,8,-4,1])

row_indices = np.arange(M)
col_indices = np.arange(N)

print(row_indices)
print(col_indices)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [174]:
model2_6.x = Var(col_indices, domain = Binary)
model2_6.constraints = ConstraintList()

In [175]:
for i in row_indices:
  model2_6.constraints.add(sum(constr_coef_A[i][j]*model2_6.x[j] for j in col_indices) <= constr_coef_rhs[i])

In [176]:
model2_6.objective = Objective(expr = summation(obj_coef_c , model2_6.x) , sense = maximize )

In [177]:
model2_6.pprint()

2 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   12 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   11 : {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

1 Var Declarations
    x : Size=11, Index=x_index
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          0 :     0 :  None :     1 : False :  True : Binary
          1 :     0 :  None :     1 : False :  True : Binary
          2 :     0 :  None :     1 : False :  True : Binary
          3 :     0 :  None :     1 : False :  True : Binary
          4 :     0 :  None :     1 : False :  True : Binary
          5 :     0 :  None :     1 : False :  True : Binary
          6 :     0 :  None :     1 : False :  True : Binary
          7 :     0 :  None :     1 : False :  True : Binary
          8 :     0 :  N

In [178]:
!apt-get install -y -qq coinor-cbc

In [179]:
opt_cbc = SolverFactory('cbc')

In [180]:
result = opt_cbc.solve(model2_6)
print(result)

print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)
print('Solver time:',result.solver.time)


Problem: 
- Name: unknown
  Lower bound: 45.0
  Upper bound: 45.0
  Number of objectives: 1
  Number of constraints: 12
  Number of variables: 11
  Number of binary variables: 11
  Number of integer variables: 11
  Number of nonzeros: 11
  Sense: maximize
Solver: 
- Status: ok
  User time: -1.0
  System time: 0.0
  Wallclock time: 0.0
  Termination condition: optimal
  Termination message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
  Statistics: 
    Branch and bound: 
      Number of bounded subproblems: 0
      Number of created subproblems: 0
    Black box: 
      Number of iterations: 0
  Error rc: 0
  Time: 0.020169496536254883
Solution: 
- number of solutions: 0
  number of solutions displayed: 0

Solver status: ok
Solver termination condition: optimal
Solver time: 0.020169496536254883


#  Exercise 2(8) Solution

In [181]:
model2_8 = ConcreteModel()

In [182]:
N = 11
M = 12

In [183]:
lb = np.array([0]*11)
ub = np.array([1]*11)

In [184]:
obj_coef_c = np.array([4,3,6,5,2,6,4,8,8,6,12])

constr_coef_A = np.array([[-4,-3,-6,-5,-2,-6,-4,-8,-8,-6,-12],
                          [0,0,1,0,0,0,0,1,0,0,0],
                          [0,1,0,0,0,0,0,0,0,1,0],
                          [0,0,1,0,0,0,0,0,1,0,0],
                          [0,0,0,0,-1,0,0,0,0,1,0],
                          [1,1,1,1,0,0,0,0,0,0,0],
                          [-1,-1,-1,-1,0,0,0,0,0,0,0],
                          [0,0,0,0,0,1,0,0,0,1,0],
                          [0,0,0,0,0,0,1,0,1,1,0],
                          [1,1,1,1,1,1,1,1,1,1,1],
                          [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                          [0,0,0,0,0,1,1,0,0,0,1]
                          ])

constr_coef_rhs = np.array([-26,1,1,1,0,2,-1,1,2,8,-4,1])

row_indices = np.arange(M)
col_indices = np.arange(N)

print(row_indices)
print(col_indices)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [185]:
model2_8.x = Var(col_indices, domain = Reals)
model2_8.constraints = ConstraintList()

In [186]:
for i in col_indices:
  model2_8.x[i].setlb(lb[i])
  model2_8.x[i].setub(ub[i])

In [187]:
for i in row_indices:
  model2_8.constraints.add(sum(constr_coef_A[i][j]*model2_8.x[j] for j in col_indices) <= constr_coef_rhs[i])

In [188]:
model2_8.objective = Objective(expr = summation(obj_coef_c , model2_8.x) , sense = maximize )

In [189]:
model2_8.pprint()

2 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   12 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   11 : {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

1 Var Declarations
    x : Size=11, Index=x_index
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          0 :     0 :  None :     1 : False :  True :  Reals
          1 :     0 :  None :     1 : False :  True :  Reals
          2 :     0 :  None :     1 : False :  True :  Reals
          3 :     0 :  None :     1 : False :  True :  Reals
          4 :     0 :  None :     1 : False :  True :  Reals
          5 :     0 :  None :     1 : False :  True :  Reals
          6 :     0 :  None :     1 : False :  True :  Reals
          7 :     0 :  None :     1 : False :  True :  Reals
          8 :     0 :  N

In [190]:
!apt-get install -y -qq coinor-cbc

In [191]:
opt_cbc = SolverFactory('cbc')

In [192]:
result = opt_cbc.solve(model2_8)
print(result)

print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)
print('Solver time:',result.solver.time)


Problem: 
- Name: unknown
  Lower bound: 45.0
  Upper bound: 45.0
  Number of objectives: 1
  Number of constraints: 13
  Number of variables: 12
  Number of nonzeros: 11
  Sense: maximize
Solver: 
- Status: ok
  User time: -1.0
  System time: 0.0
  Wallclock time: 0.0
  Termination condition: optimal
  Termination message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
  Statistics: 
    Branch and bound: 
      Number of bounded subproblems: None
      Number of created subproblems: None
    Black box: 
      Number of iterations: 6
  Error rc: 0
  Time: 0.02167534828186035
Solution: 
- number of solutions: 0
  number of solutions displayed: 0

Solver status: ok
Solver termination condition: optimal
Solver time: 0.02167534828186035
