## **Exercise 2 Solution**

# Exercise 2(1)

For solving this problem, we can associate a decision variable $x_{ij}$ for denoting the factory $i$ assign to a location $j$.

Let $i$ take values from the set $\{1,2,3,4,5,6,7,8,9,10,11,12\}$ corresponding to factory number. 
Let $j$ take values from the set $\{1,2,3,4,5,6,7,8,9,10,11,12\}$ corresponding to location number.

here we have assign each location have one factory so decision varible $x_{ij}$ have only two value {0,1} means if facory is not assign then take vlaue 0 and if assign the take value 1. 

Now we shall formulate the objective function. Since $x_{ij}$ facory $i$ is assign at location $j$, and since we know the assigning the cost of each factory $i$ is assign the location $j$, we have minimize the total asigning cost:


min $A_{ij}$ * $x_{ij}$

where A = [[21 25 18 19 23 24 16 17 21 23 19 21]


[19 22 19 19 23 21 15 20 16 17 17 24]


[21 19 20 18 22 24 14 16 18 16 20 24]


[19 22 17 17 22 22 18 18 20 21 23 23]


[18 22 15 15 23 23 21 25 24 19 21 23]


[23 19 19 14 24 21 23 21 20 20 22 19]


[21 16 27 17 26 27 16 19 24 20 20 23]


[22 17 21 15 23 24 24 20 22 19 23 21]


[23 24 18 19 22 23 21 18 23 15 25 21]


[18 21 21 18 26 24 18 17 18 20 21 20]


[19 12 21 19 23 20 22 19 17 19 20 24]


[18 22 24 17 21 28 18 16 22 24 25 24]]

s.t.

\begin{align}
\sum_{j=1}^{12} x_{1j} &= 1 \nonumber \\
\sum_{j=1}^{12} x_{2j} &= 1 \nonumber \\
\sum_{j=1}^{12} x_{3j} &= 1 \nonumber \\
\sum_{j=1}^{12} x_{4j} &= 1 \nonumber \\
\sum_{j=1}^{12} x_{5j} &= 1 \nonumber \\
\sum_{j=1}^{12} x_{6j} &= 1 \nonumber \\
\sum_{j=1}^{12} x_{7j} &= 1 \nonumber \\
\sum_{j=1}^{12} x_{8j} &= 1 \nonumber \\
\sum_{j=1}^{12} x_{9j} &= 1 \nonumber \\
\sum_{j=1}^{12} x_{10j} &= 1 \nonumber \\
\sum_{j=1}^{12} x_{11j} &= 1 \nonumber \\
\sum_{j=1}^{12} x_{12j} &= 1 \nonumber \\
\text{ and } \nonumber \\ 
\sum_{i=1}^{12} x_{i1} &= 1 \nonumber \\
\sum_{i=1}^{12} x_{i2} &= 1 \nonumber \\
\sum_{i=1}^{12} x_{i3} &= 1 \nonumber \\
\sum_{i=1}^{12} x_{i4} &= 1 \nonumber \\
\sum_{i=1}^{12} x_{i5} &= 1 \nonumber \\
\sum_{i=1}^{12} x_{i6} &= 1 \nonumber \\
\sum_{i=1}^{12} x_{i7} &= 1 \nonumber \\
\sum_{i=1}^{12} x_{i8} &= 1 \nonumber \\
\sum_{i=1}^{12} x_{i9} &= 1 \nonumber \\
\sum_{i=1}^{12} x_{i10} &= 1 \nonumber \\
\sum_{i=1}^{12} x_{i11} &= 1 \nonumber \\
\sum_{i=1}^{12} x_{i12} &= 1 \nonumber \\
\text{ and } \nonumber \\ 
x_{ij} &= {0,1} \ \forall i \in \{1,2,3,4,5,6,7,8,9,10,11,12\}, \ \forall j \in \{1,2,3,4,5,6,7,8,9,10,11,12\}. \nonumber
\end{align}





In [ ]:
!pip install -q pyomo
from pyomo.environ import*
import numpy as np

In [ ]:
data_txtfile = np.loadtxt("lab6_ex2.txt",delimiter=" ")

In [ ]:
print(data_txtfile)
print('Num rows:',data_txtfile.shape[0])
print('Num cols:',data_txtfile.shape[1])

[[21. 25. 18. 19. 23. 24. 16. 17. 21. 23. 19. 21.]
 [19. 22. 19. 19. 23. 21. 15. 20. 16. 17. 17. 24.]
 [21. 19. 20. 18. 22. 24. 14. 16. 18. 16. 20. 24.]
 [19. 22. 17. 17. 22. 22. 18. 18. 20. 21. 23. 23.]
 [18. 22. 15. 15. 23. 23. 21. 25. 24. 19. 21. 23.]
 [23. 19. 19. 14. 24. 21. 23. 21. 20. 20. 22. 19.]
 [21. 16. 27. 17. 26. 27. 16. 19. 24. 20. 20. 23.]
 [22. 17. 21. 15. 23. 24. 24. 20. 22. 19. 23. 21.]
 [23. 24. 18. 19. 22. 23. 21. 18. 23. 15. 25. 21.]
 [18. 21. 21. 18. 26. 24. 18. 17. 18. 20. 21. 20.]
 [19. 12. 21. 19. 23. 20. 22. 19. 17. 19. 20. 24.]
 [18. 22. 24. 17. 21. 28. 18. 16. 22. 24. 25. 24.]]
Num rows: 12
Num cols: 12


In [ ]:
model_lab6 = ConcreteModel()

In [ ]:
data_txtfile.shape

(12, 12)

In [ ]:
row_indices = range(data_txtfile.shape[0])
col_indices = range(data_txtfile.shape[1])

In [ ]:
model_lab6.x = Var(row_indices,col_indices,domain = Binary)

In [ ]:
model_lab6.objective = Objective(expr=sum(model_lab6.x[i,j]*data_txtfile[i,j] for i in row_indices for j in col_indices), sense=minimize)

In [ ]:
model_lab6.constraints = ConstraintList() 

In [ ]:
for i in row_indices:
  model_lab6.constraints.add(expr=sum(model_lab6.x[i,j] for j in col_indices) == 1)

for i in row_indices:
   model_lab6.constraints.add(expr=sum(model_lab6.x[j,i] for j in col_indices)==1) 

In [ ]:
model_lab6.pprint()

4 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   24 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24}
    x_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain              : Size : Members
        None :     2 : x_index_0*x_index_1 :  144 : {(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (2, 11), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (3, 11), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 10), (4, 11), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (5, 10), (5, 11

In [ ]:
!apt-get install -y -qq coinor-cbc

Selecting previously unselected package coinor-libcoinutils3v5.
(Reading database ... 155569 files and directories currently installed.)
Preparing to unpack .../0-coinor-libcoinutils3v5_2.10.14+repack1-1_amd64.deb ...
Unpacking coinor-libcoinutils3v5 (2.10.14+repack1-1) ...
Selecting previously unselected package coinor-libosi1v5.
Preparing to unpack .../1-coinor-libosi1v5_0.107.9+repack1-1_amd64.deb ...
Unpacking coinor-libosi1v5 (0.107.9+repack1-1) ...
Selecting previously unselected package coinor-libclp1.
Preparing to unpack .../2-coinor-libclp1_1.16.11+repack1-1_amd64.deb ...
Unpacking coinor-libclp1 (1.16.11+repack1-1) ...
Selecting previously unselected package coinor-libcgl1.
Preparing to unpack .../3-coinor-libcgl1_0.59.10+repack1-1_amd64.deb ...
Unpacking coinor-libcgl1 (0.59.10+repack1-1) ...
Selecting previously unselected package coinor-libcbc3.
Preparing to unpack .../4-coinor-libcbc3_2.9.9+repack1-1_amd64.deb ...
Unpacking coinor-libcbc3 (2.9.9+repack1-1) ...
Selecting p

In [ ]:
opt_cbc = SolverFactory('cbc')

In [ ]:
result = opt_cbc.solve(model_lab6)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal


In [ ]:
# display solution
print('\nObjective = ', model_lab6.objective())

print('\nDecision Variables')
for i in row_indices:
  for j in col_indices:
    if model_lab6.x[i,j].value==1:
      print('factory' ,i+1, 'is located to',j+1)

print('\nConstraints')
model_lab6.constraints.display()


Objective =  204.0

Decision Variables
factory 1 is located to 11
factory 2 is located to 9
factory 3 is located to 8
factory 4 is located to 6
factory 5 is located to 3
factory 6 is located to 12
factory 7 is located to 7
factory 8 is located to 4
factory 9 is located to 10
factory 10 is located to 1
factory 11 is located to 2
factory 12 is located to 5

Constraints
constraints : Size=24
    Key : Lower : Body : Upper
      1 :   1.0 :  1.0 :   1.0
      2 :   1.0 :  1.0 :   1.0
      3 :   1.0 :  1.0 :   1.0
      4 :   1.0 :  1.0 :   1.0
      5 :   1.0 :  1.0 :   1.0
      6 :   1.0 :  1.0 :   1.0
      7 :   1.0 :  1.0 :   1.0
      8 :   1.0 :  1.0 :   1.0
      9 :   1.0 :  1.0 :   1.0
     10 :   1.0 :  1.0 :   1.0
     11 :   1.0 :  1.0 :   1.0
     12 :   1.0 :  1.0 :   1.0
     13 :   1.0 :  1.0 :   1.0
     14 :   1.0 :  1.0 :   1.0
     15 :   1.0 :  1.0 :   1.0
     16 :   1.0 :  1.0 :   1.0
     17 :   1.0 :  1.0 :   1.0
     18 :   1.0 :  1.0 :   1.0
     19 :   1.0 : 

# Exercise 2(8)

factory 1 is located to 11

factory 2 is located to 9

factory 3 is located to 8

factory 4 is located to 6

factory 5 is located to 3

factory 6 is located to 12

factory 7 is located to 7

factory 8 is located to 4

factory 9 is located to 10

factory 10 is located to 1

factory 11 is located to 2

factory 12 is located to 5

# Exercise 2(9)

In [ ]:
model_lab6.x.domain = Reals

In [ ]:
model_lab6.x.setub(1)
model_lab6.x.setlb(0)

In [ ]:
result = opt_cbc.solve(model_lab6)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal


In [ ]:
# display solution
print('\nObjective = ', model_lab6.objective())

print('\nDecision Variables')
for i in row_indices:
  for j in col_indices:
    if model_lab6.x[i,j].value==1:
      print('factory' ,i+1, 'is located to',j+1)

print('\nConstraints')
model_lab6.constraints.display()


Objective =  204.0

Decision Variables
factory 1 is located to 11
factory 2 is located to 9
factory 3 is located to 8
factory 4 is located to 6
factory 5 is located to 3
factory 6 is located to 12
factory 7 is located to 7
factory 8 is located to 4
factory 9 is located to 10
factory 10 is located to 1
factory 11 is located to 2
factory 12 is located to 5

Constraints
constraints : Size=24
    Key : Lower : Body : Upper
      1 :   1.0 :  1.0 :   1.0
      2 :   1.0 :  1.0 :   1.0
      3 :   1.0 :  1.0 :   1.0
      4 :   1.0 :  1.0 :   1.0
      5 :   1.0 :  1.0 :   1.0
      6 :   1.0 :  1.0 :   1.0
      7 :   1.0 :  1.0 :   1.0
      8 :   1.0 :  1.0 :   1.0
      9 :   1.0 :  1.0 :   1.0
     10 :   1.0 :  1.0 :   1.0
     11 :   1.0 :  1.0 :   1.0
     12 :   1.0 :  1.0 :   1.0
     13 :   1.0 :  1.0 :   1.0
     14 :   1.0 :  1.0 :   1.0
     15 :   1.0 :  1.0 :   1.0
     16 :   1.0 :  1.0 :   1.0
     17 :   1.0 :  1.0 :   1.0
     18 :   1.0 :  1.0 :   1.0
     19 :   1.0 : 

# Exercise 2(10)

the optimal solution cost for both problem is same. and the value of the varible still integer valued because no changes in solution in binary domain and real domain. or 1 factory assign 1 locaton.

# Exercise 2(12)

Now suppose that, due to some reason, facility 3 cannot be assigned to location 4, facility 9 cannot be assigned to location 6 and facility 4 cannot be assigned to location 10. this is change in txt file while I am very much increase the setup cost.  


In [ ]:
data_txtfile[2,3] = 99999999
data_txtfile[8,5] = 999999999
data_txtfile[3,9] = 9999999999

In [ ]:
model_lab6.x.setub(-np.inf)
model_lab6.x.setlb(np.inf)

In [ ]:
model_lab6.x.domain = Binary

In [ ]:
result = opt_cbc.solve(model_lab6)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

  - termination condition: infeasible
  - message from solver: <undefined>


Solver status: warning
Solver termination condition: infeasible


In [ ]:
# display solution
print('\nObjective = ', model_lab6.objective())

print('\nDecision Variables')
for i in row_indices:
  for j in col_indices:
    if model_lab6.x[i,j].value==1:
      print('factory' ,i+1, 'is located to',j+1)

print('\nConstraints')
model_lab6.constraints.display()


Objective =  204.0

Decision Variables
factory 1 is located to 11
factory 2 is located to 9
factory 3 is located to 8
factory 4 is located to 6
factory 5 is located to 3
factory 6 is located to 12
factory 7 is located to 7
factory 8 is located to 4
factory 9 is located to 10
factory 10 is located to 1
factory 11 is located to 2
factory 12 is located to 5

Constraints
constraints : Size=24
    Key : Lower : Body : Upper
      1 :   1.0 :  1.0 :   1.0
      2 :   1.0 :  1.0 :   1.0
      3 :   1.0 :  1.0 :   1.0
      4 :   1.0 :  1.0 :   1.0
      5 :   1.0 :  1.0 :   1.0
      6 :   1.0 :  1.0 :   1.0
      7 :   1.0 :  1.0 :   1.0
      8 :   1.0 :  1.0 :   1.0
      9 :   1.0 :  1.0 :   1.0
     10 :   1.0 :  1.0 :   1.0
     11 :   1.0 :  1.0 :   1.0
     12 :   1.0 :  1.0 :   1.0
     13 :   1.0 :  1.0 :   1.0
     14 :   1.0 :  1.0 :   1.0
     15 :   1.0 :  1.0 :   1.0
     16 :   1.0 :  1.0 :   1.0
     17 :   1.0 :  1.0 :   1.0
     18 :   1.0 :  1.0 :   1.0
     19 :   1.0 : 

After solving this problem, solution is same because already have not assign the facility 3 to lpcation 4,facility 9 to lpcation 6 and facility 4 to lpcation 10